name: tag-release
on:
  push:
    branches:
      - master
      - 'release-*'
    tags:
      - "v*"
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.2

      - name: Build Go Binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o ecr-credential-provider cmd/ecr-credential-provider/*.go
      - uses: actions/upload-artifact@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ecr-credential-provider
          path: ecr-credential-provider

      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: |
            AWS Cloud Provider
            
            The cloud provider now runs out-of-tree in a new component called aws-cloud-controller-manager.
            The external provider preserves all existing behavior/functionality from the legacy in-tree provider.
            
            ## CHANGELOG
            See [CHANGELOG](https://github.com/kubernetes/cloud-provider-aws/blob/master/docs/CHANGELOG.md) for full list of changes.
          draft: false
          prerelease: false

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ecr-credential-provider
          asset_name: ecr-credential-provider
          asset_content_type: application/octet-stream
